fuzz:
	@go test -fuzz=FuzzAcctReply			-fuzztime=600s	.
	@go test -fuzz=FuzzAcctRequest			-fuzztime=600s	.
	@go test -fuzz=FuzzAuthenContinue		-fuzztime=600s	.
	@go test -fuzz=FuzzAuthenReply			-fuzztime=600s	.
	@go test -fuzz=FuzzAuthenStart			-fuzztime=600s	.
	@go test -fuzz=FuzzAuthorReply			-fuzztime=600s	.
	@go test -fuzz=FuzzAuthorRequest		-fuzztime=600s	.
	@go test -fuzz=FuzzPacket				-fuzztime=600s	.
